name: expiration-deploy
on:
  push:
    branches: 
      - master 
    paths:
      - 'expiration/**' 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses:  actions/checkout@v2
      - run: cd expiration && docker build -t mmajd/expiration . 
      - run: docker login -u $DOCKER_USER -p $DOCKER_PSWD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }} 
          DOCKER_PSWD: ${{ secrets.DOCKER_PSWD }} 
      - run: docker push mmajd/expiration
